### ISSUE TITLE
Main container substracts sidebar width even if sidebar is empty

### ISSUE THREAD

**Issue by isotrope** [skyshab/taproot#4] opened 2019-04-09 15:04 UTC
Content width of `main.app-main` is substracting the sidebar width, even when there's no sidebar (no widgets).
It makes it float in the middle, unaligned with the header/footer.
![screencapture-taproot-local-2019-04-09-09_39_58](https://user-images.githubusercontent.com/1068911/55811241-d411e100-5ab6-11e9-9b0d-cafc78a34c09.png)

**Comment by skyshab** [comment] 2019-06-18 11:59
Closing because this is a "feature" not a bug. 

"Wide" blocks will be aligned with the header/footer. Standard blocks are aligned in the center.

**Closed as completed by skyshab** 2019-06-18 11:59 UTC
